name: self-hosted

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: population-sr
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Create .env
        run: cp /home/deploy/config/.env ./.env
      - name: Make up
        run: make up
