name: self-hosted

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: deploy_prod
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Create .env
        run: cp /home/deploy/appconfig/.env ./.env
      - name: Make up
        run: make up
